language: node_js
node_js:
- 6
- 8
- 10
script:
- export NODE_ENV=test
- npm run build
- npm test
- npm run coverage
before_deploy:
- npm run clean
- NODE_ENV=production npm run build
deploy:
  provider: npm
  email: karim@alibhai.co
  api_key:
    secure: OR224xlQE5zbVokZqPCdgpiJdG7YxqmBcmVI8hS5/qP4idKw1P5U1C2VUKA+STwFer6MFUmE6jA8XLwHYbSCsVj7q3GNPfmsx5oYH3dd66qNu9CCfozzyO+f02TImw6eb89xO2vvYAoWQO/Kt0r+TfAj3CknkwyJC5/hrWwMpolQ5Rx7aHJj4MMg0Y0yg9qZ16RiUOk57MTidRzOzATNt3KoZm/jwHgJFxyej8Y/CvR/mk6Nxao5VE5ZxFyaQkFFjdNsIG4Nll+lILfPourIlWtaioF3jVaWXXT+uHQtat1Yk7R2dLrinl4mcYH/Z0BOAk/C5IHSR7orJoessdKAJjy9pwfeVX9DHbBjDsxyoANLTsXyOcVSDfJbJLokP0Oq6JfRRCjIpsT6JvI2T8fwxci+4iz+5zQiZV51VqmEmqn8z0hxY2iw3Qkq5p2BzefnhgL3EcHZ9h5zIb52Jy406CeKc5UOI31DU1NJhMy7jhfEyewsErQ6op7odOx8PkEMBJxLOOz46cUguRGOnBk1js/DdiCMXA9JVjvjFjLL35Q3dzjFN700GFQhhgwVSYwb6DaFhl1IUmC/J4camezq8Xl+U2k7sdneOEKBfJ49DbBsHsq/j2deQ1a8PZtyjMtIOMPdMnZyD0/BOUy7Bv+CqZH4rRfwRM6/ogwlj+42iRE=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 6
    repo: karimsa/rsxjs

