name: CI

on:
  push:
  issue_comment:
    types: [created]

env:
  CI: true
  NODE_ENV: test
  NPM_AUTH_TOKEN: 

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [8, 10, 12]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: ${{ matrix.node }}
    # - uses: actions/cache@v1
    #   if: always()
    #   with:
    #     path: ~/.cache
    #     key: ${{ runner.os }}-home-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: |
        set -e
        npm run build
        npm test
        npm run coverage
    - name: Publish
      if: "startsWith(github.ref, 'refs/tags/v') && matrix.node == 8"
      run: |
        set -e
        npm run clean
        NODE_ENV=production npm run build
        echo "" > ~/.npmrc
        npm publish
